name: Test

on:
  push:
    branches: main
  pull_request:

jobs:
  test_google-cloud-swift:
    name: Test google-cloud-swift
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.10", "6.0"]
    steps:
      - uses: vapor/swiftly-action@v0.1
        with:
          toolchain: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: start emulator servers
        run: docker compose up -d
      - uses: actions/cache@v4
        with:
          path: |
            .build/checkouts
            .build/repositories
          key: google-cloud-swift_build_${{ runner.os }}_${{ hashFiles('Package.resolved') }}
      - run: swift build
      - name: swift test
        run: ./run_test.sh
